theme: jekyll-theme-minimal
title: AI Saint
description: Policies and Documentation for AI Saint App
show_downloads: false
google_analytics:
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true 